In [ ]:
Ans.1  Yes, there is a difference in the data type of the list_ and array_list variables. list_ is a Python list, and array_list
is a NumPy array. You can print the data types of both variables using the type() function in Python. Here's the code to do that
:

In [1]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))

Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


In [ ]:
Ans.2  You can use a loop to iterate through each element of both the list_ and array_list variables and print the data type of 
each element. Here's the code to do that:

In [2]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print data types of elements in list_
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

# Print data types of elements in array_list
print("\nData types of elements in array_list:")
for element in array_list:
    print(type(element))

Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [ ]:
Ans.3 Yes, there will be a difference in the data types of the elements present in list_ and array_list after the change in 
array_list where we specify the data type as int. In list_, the elements are originally strings, but in array_list, the elements
will be converted to integers.
Here's the code to print the data types of each and every element present in both variables list_ and array_list after the 
change:

In [3]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Print data types of elements in list_
print("Data types of elements in list_:")
for element in list_:
    print(type(element))

# Print data types of elements in array_list
print("\nData types of elements in array_list:")
for element in array_list:
    print(type(element))

Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


In [ ]:
Ans.4  You can find the shape and size of the NumPy array num_array using the shape and size attributes, respectively. Here's 
the code to do that:

In [4]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# (i) Find the shape of num_array
shape = num_array.shape
print("Shape of num_array:", shape)

# (ii) Find the size of num_array
size = num_array.size
print("Size of num_array:", size)

Shape of num_array: (2, 3)
Size of num_array: 6


In [ ]:
Ans.5  You can create a NumPy array of a 3x3 matrix containing zeros only using the numpy.zeros function. Here's the code to do 
that:

In [5]:
import numpy as np

# Create a 3x3 array filled with zeros
zero_matrix = np.zeros((3, 3))

print(zero_matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
Ans.6  You can create a 5x5 identity matrix using the numpy.eye function. Here's the code to create an identity matrix of shape 
(5,5):

In [6]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
