In [1]:
#1. TensorFlow primarily uses tensors as the fundamental data structure, which can be thought of as multi-dimensional arrays. 
# Tensors are at the core of TensorFlow, and there are different data structures that can be created from tensors for various 
# purposes. Some of the common data structures and their examples in TensorFlow include:

#a. Constant: Constants are tensors whose values cannot be changed after creation. They are typically used for storing fixed 
#  values like hyperparameters, model configuration, or any other constant data.
    
    #Examples:
import tensorflow as tf
constant_tensor = tf.constant([1, 2, 3])


In [2]:
#b. Variable: Variables are tensors that can be updated during training. They are used to represent model parameters, and their 
#   values can be modified using operations like gradient descent during training.

#Example:

import tensorflow as tf
variable_tensor = tf.Variable([1.0, 2.0, 3.0])


In [ ]:
#c. Placeholder (In older versions, replaced by tf.data): Placeholders are used for feeding input data into a TensorFlow 
#  computation graph. They allow you to provide data values later during session execution.

# Example (older version):

import tensorflow as tf
x = tf.placeholder(tf.float32, shape=(None, 3))

In [ ]:
#d. SparseTensor: Sparse tensors are used to efficiently represent and manipulate data with a large number of zeros, such as 
# sparse feature data in machine learning.

#Example:
import tensorflow as tf
indices = tf.constant([[0, 1], [2, 3]])
values = tf.constant([4, 5], dtype=tf.int32)
shape = tf.constant([3, 4])
sparse_tensor = tf.sparse.SparseTensor(indices, values, shape)

In [5]:
#2. TensorFlow Constant vs. TensorFlow Variable:

# TensorFlow Constant: Constants in TensorFlow are immutable; once you define their value, it cannot be changed. They are 
# typically used for storing fixed values, such as model hyperparameters or configuration settings. Changing a constant's value 
# requires creating a new constant.
# Example:

import tensorflow as tf
constant_tensor = tf.constant(2.0)

In [6]:
# TensorFlow Variable: Variables are mutable and are used for representing model parameters that need to be updated during 
# training. They are typically initialized with an initial value and can be modified during training by applying operations that
# update their values, such as gradient descent.
# Example:

import tensorflow as tf
variable_tensor = tf.Variable(2.0)
updated_variable = variable_tensor.assign(3.0)

In [ ]:
#3. Matrix Operations in TensorFlow:

Matrix Addition: In TensorFlow, you can perform matrix addition using the tf.add or the + operator
    
Matrix Multiplication: Matrix multiplication is performed using tf.matmul or the @ operator for matrix multiplication.
    
Element-wise Operations: Element-wise operations like element-wise addition, subtraction, multiplication, and division can be 
    performed using standard mathematical operators or TensorFlow functions like tf.add, tf.subtract, tf.multiply, and tf.divide

In [10]:
#Part 2: Practical Implementation
#Task 1: Creating and Manipulating Matrices


import tensorflow as tf

# Task 1: Create and display matrix A (3x3) with random values using random_normal
matrix_shape_A = (3, 3)
matrix_A = tf.random.normal(shape=matrix_shape_A)
print("Matrix A:")
print(matrix_A.numpy())

# Task 2: Create and display matrix B (3x3) with truncated normal values (to match A)
matrix_shape_B = (3, 3)
matrix_B = tf.random.truncated_normal(shape=matrix_shape_B)
print("\nMatrix B:")
print(matrix_B.numpy())

# Task 3: Create and display matrix C (2x3) with specified mean and standard deviation
matrix_shape_C = (2, 3)
mean = 3.0
stddev = 0.5
matrix_C = tf.random.normal(shape=matrix_shape_C, mean=mean, stddev=stddev)
print("\nMatrix C:")
print(matrix_C.numpy())

# Task 4: Perform matrix addition between A and B to get D
matrix_D = tf.add(matrix_A, matrix_B)
print("\nMatrix D (Result of A + B):")
print(matrix_D.numpy())

# Task 5: Perform matrix multiplication between C and D to get E
matrix_E = tf.matmul(matrix_C, matrix_D)
print("\nMatrix E (Result of C * D):")
print(matrix_E.numpy())


Matrix A:
[[ 0.6485863  -1.0935895   0.33377147]
 [ 1.7396878  -0.5766993   0.5178998 ]
 [-0.7307785  -0.5511436   0.43127546]]

Matrix B:
[[-1.4412652   0.96340454  1.8773173 ]
 [-0.6810077   1.2411076   0.8172286 ]
 [ 0.6886203  -1.5216138   0.8150834 ]]

Matrix C:
[[2.852809  3.2838416 2.869962 ]
 [2.763329  2.1195412 4.3479857]]

Matrix D (Result of A + B):
[[-0.79267895 -0.13018501  2.2110887 ]
 [ 1.05868     0.66440827  1.3351284 ]
 [-0.04215819 -2.0727575   1.2463589 ]]

Matrix E (Result of C * D):
[[ 1.0941837  -4.1383166  14.269166  ]
 [-0.12981994 -7.963823   14.358976  ]]


In [11]:
#Task 2: Performing Additional Matrix Operations

import tensorflow as tf

# Task 1: Create and display matrix F (3x3) with random values using random_uniform
matrix_shape_F = (3, 3)
matrix_F = tf.random.uniform(shape=matrix_shape_F)
print("Matrix F:")
print(matrix_F.numpy())

# Task 2: Calculate the transpose of matrix F and store the result in matrix G
matrix_G = tf.transpose(matrix_F)
print("\nMatrix G (Transpose of F):")
print(matrix_G.numpy())

# Task 3: Calculate the element-wise exponential of matrix F and store the result in matrix H
matrix_H = tf.exp(matrix_F)
print("\nMatrix H (Element-wise Exponential of F):")
print(matrix_H.numpy())

# Task 4: Create matrix I by concatenating F and G horizontally
matrix_I = tf.concat([matrix_F, matrix_G], axis=1)
print("\nMatrix I (Concatenation of F and G horizontally):")
print(matrix_I.numpy())

# Task 5: Create matrix J by concatenating F and H vertically
matrix_J = tf.concat([matrix_F, matrix_H], axis=0)
print("\nMatrix J (Concatenation of F and H vertically):")
print(matrix_J.numpy())

Matrix F:
[[0.4217906  0.97683215 0.77904487]
 [0.647856   0.48958325 0.49193704]
 [0.79610765 0.925048   0.6899724 ]]

Matrix G (Transpose of F):
[[0.4217906  0.647856   0.79610765]
 [0.97683215 0.48958325 0.925048  ]
 [0.77904487 0.49193704 0.6899724 ]]

Matrix H (Element-wise Exponential of F):
[[1.5246892 2.656029  2.1793897]
 [1.9114383 1.6316361 1.6354811]
 [2.216895  2.5219893 1.9936604]]

Matrix I (Concatenation of F and G horizontally):
[[0.4217906  0.97683215 0.77904487 0.4217906  0.647856   0.79610765]
 [0.647856   0.48958325 0.49193704 0.97683215 0.48958325 0.925048  ]
 [0.79610765 0.925048   0.6899724  0.77904487 0.49193704 0.6899724 ]]

Matrix J (Concatenation of F and H vertically):
[[0.4217906  0.97683215 0.77904487]
 [0.647856   0.48958325 0.49193704]
 [0.79610765 0.925048   0.6899724 ]
 [1.5246892  2.656029   2.1793897 ]
 [1.9114383  1.6316361  1.6354811 ]
 [2.216895   2.5219893  1.9936604 ]]
